version: "3.8"

name: singlestore-kafka-dev
services:
  singlestoredb-dev:
    image: ghcr.io/singlestore-labs/singlestoredb-dev
    ports:
      - 3307:3306
      - 8086:8080
      - 9000:9000
    environment:
      ROOT_PASSWORD: 1234

#      Replace it with your single store account license
      SINGLESTORE_LICENSE: ${SINGLESTORE_LICENSE}

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: cp-zookeeper-container-dev
    ports:
      - 22181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: cp-kafka-container-dev
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


    volumes:
    - singlestore-data:/var/lib/memsql
volumes:
  singlestore-data:
    driver: local


