server:
  port: 8086
spring:
  datasource:
    password: 1234
    url: jdbc:singlestore://localhost:3307/sa?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.singlestore.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.format_sql: true
    show-sql: true
  profiles:
    active: dev
  application:
    name: test-containers
  kafka:
    bootstrapAddress: localhost:29092
    consumer:
      group-id: me
groupId: me


---
server:
  port: 8082
spring:
  docker:
    compose:
      enabled: true
      file: docker-compose-singlestore.yml
      stop:
        command: stop
        timeout: 0
  jpa:
    hibernate:
      ddl-auto: create
  config:
    activate:
      on-profile: dev
    groupId: me
---
spring:
  docker:
    compose:
      skip:
        in-tests: false
      enabled: true
      file: docker-compose-singlestore-test.yml
      stop:
        command: down
        timeout: 0
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create



